export const ALL_PRODUCT = "ALL_PRODUCT"
export const ADD_CART_ITEM  = "ADD_CART_ITEM";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM"
export const UPDATE_QUANTITY_CART_ITEM = "UPDATE_QUANTITY_CART_ITEM"

export const CLOSE_MINI_CART = "CLOSE_MINI_CART"
export const OPEN_MINI_CART = "OPEN_MINI_CART"

export const FILTER_PRICE_PRODUCT = "FILTER_PRICE_PRODUCT"
export const  SORT_PRODUCT = "SORT_PRODUCT"